### ISSUE TITLE
Chrome + Open in GMail

### ISSUE THREAD

**Issue by 100ArchiveTeam** [0xmmo/jquery-confirm-mailto#1]
No dialog— goes straight to new gmail window. No extension, gmail set as auto email client

**Comment by jamesdelaneyie** [comment]
Sorry, was on wrong account, this was from me

**Comment by 0xmmo** [comment]
Could not replicate. I set Gmail as default email client through Chrome's protocol handler.
Can you indicate the browser, version and if you're using an extension to set gmail as default client?
